# Generated by Django 4.2.1 on 2023-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_alter_meeting_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='dept',
            field=models.CharField(max_length=100),
        ),
    ]
