# Generated by Django 4.2.1 on 2023-06-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('basic_pay', models.IntegerField()),
                ('overtime_pay', models.IntegerField()),
                ('tax_deducted', models.IntegerField()),
                ('netpay', models.IntegerField()),
            ],
        ),
    ]
